# Generated by Django 6.1 on 2026-08-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Canonical order, Genesis=1')),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=3)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StrongsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. G25 or H1254', max_length=10, unique=True)),
                ('language', models.CharField(choices=[('greek', 'Greek'), ('hebrew', 'Hebrew')], max_length=6)),
                ('lemma', models.CharField(blank=True, help_text='Word in original script', max_length=100)),
                ('translit', models.CharField(blank=True, help_text='Transliteration', max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('derivation', models.TextField(blank=True)),
                ('strongs_def', models.TextField(blank=True, help_text="Strong's own definition")),
                ('kjv_def', models.TextField(blank=True, help_text="How the KJV renders this word, e.g. '(be-)love(-ed)'. Used for reverse word-lookup since we don't have a verse-tagged text.")),
            ],
            options={
                'verbose_name_plural': 'Strongs entries',
                'indexes': [models.Index(fields=['number'], name='bible_stron_number_a2c8d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse_number', models.PositiveSmallIntegerField()),
                ('translation', models.CharField(default='KJV', max_length=10)),
                ('text', models.TextField(help_text='Plain verse text, no markup')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.book')),
            ],
            options={
                'ordering': ['book__order', 'chapter', 'verse_number'],
            },
        ),
        migrations.CreateModel(
            name='CrossReferenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_book_start', models.CharField(max_length=50)),
                ('to_chapter_start', models.PositiveSmallIntegerField()),
                ('to_verse_start', models.PositiveSmallIntegerField()),
                ('to_book_end', models.CharField(max_length=50)),
                ('to_chapter_end', models.PositiveSmallIntegerField()),
                ('to_verse_end', models.PositiveSmallIntegerField()),
                ('votes', models.IntegerField(help_text='Crowd-sourced relevance score; can be negative')),
                ('from_verse', models.ForeignKey(help_text='The verse this cross-reference is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_cross_references', to='bible.verse')),
            ],
            options={
                'ordering': ['-votes'],
            },
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_label', models.CharField(help_text="e.g. 'Romans 5:8'", max_length=60)),
                ('tag', models.CharField(help_text='Short theme label, e.g. "God\'s Love"', max_length=60)),
                ('text', models.TextField()),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='bible.verse')),
            ],
        ),
        migrations.CreateModel(
            name='ConcordanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_term', models.CharField(max_length=50)),
                ('original_word', models.CharField(help_text="e.g. 'agapaō (ἀγαπάω)'", max_length=100)),
                ('strongs_number', models.CharField(help_text='e.g. G25 or H7462', max_length=10)),
                ('occurrence_count', models.CharField(help_text="Display string for total occurrences across scripture, e.g. '143+'", max_length=10)),
                ('strongs_entry', models.ForeignKey(blank=True, help_text='Optional link to the full lexicon entry for richer display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concordance_entries', to='bible.strongsentry')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concordance_entries', to='bible.verse')),
            ],
        ),
        migrations.CreateModel(
            name='WordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Word order within the original-language verse')),
                ('original_word', models.CharField(help_text='Greek/Hebrew word as it appears, with accents', max_length=100)),
                ('transliteration', models.CharField(blank=True, max_length=100)),
                ('gloss', models.CharField(blank=True, help_text='English gloss for this specific word occurrence', max_length=200)),
                ('strongs_number', models.CharField(help_text='e.g. G2889', max_length=10)),
                ('morphology', models.CharField(blank=True, help_text='Parsing code, e.g. N-ASM', max_length=50)),
                ('strongs_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_tags', to='bible.strongsentry')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_tags', to='bible.verse')),
            ],
            options={
                'ordering': ['verse', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['book', 'chapter', 'verse_number', 'translation'], name='bible_verse_book_id_8bea54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('book', 'chapter', 'verse_number', 'translation')},
        ),
        migrations.AddIndex(
            model_name='crossreferencelink',
            index=models.Index(fields=['from_verse', '-votes'], name='bible_cross_from_ve_91012a_idx'),
        ),
        migrations.AddIndex(
            model_name='concordanceentry',
            index=models.Index(fields=['strongs_number'], name='bible_conco_strongs_046863_idx'),
        ),
        migrations.AddIndex(
            model_name='concordanceentry',
            index=models.Index(fields=['english_term'], name='bible_conco_english_e8c2be_idx'),
        ),
        migrations.AddIndex(
            model_name='wordtag',
            index=models.Index(fields=['verse', 'position'], name='bible_wordt_verse_i_35401e_idx'),
        ),
        migrations.AddIndex(
            model_name='wordtag',
            index=models.Index(fields=['strongs_number'], name='bible_wordt_strongs_cdb88c_idx'),
        ),
    ]
