# Generated by Django 5.2 on 2026-09-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KjvStrongsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Word order within the KJV English verse text')),
                ('surface_word', models.CharField(help_text='The KJV word as displayed, including punctuation', max_length=50)),
                ('strongs_number', models.CharField(help_text='e.g. G2889', max_length=10)),
                ('strongs_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kjv_strongs_tags', to='bible.strongsentry')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kjv_strongs_tags', to='bible.verse')),
            ],
            options={
                'ordering': ['verse', 'position'],
                'indexes': [models.Index(fields=['verse', 'position'], name='bible_kjvst_verse_i_f8af66_idx'), models.Index(fields=['strongs_number'], name='bible_kjvst_strongs_192072_idx')],
            },
        ),
    ]
