# Generated by Django 5.2 on 2026-09-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_kjvstrongstag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtag',
            name='kjv_render_text',
            field=models.CharField(blank=True, default=None, help_text="The actual English phrase the KJV renders for this word, sourced from tahmmee/interlinear_bibledata, matched by original-language word order + Strong's number against this row. NULL = not yet cross-referenced. '' (empty string) = cross-referenced and confirmed the KJV does not render this word as a separate word (e.g. an untranslated article). A non-empty string = the KJV wording for this word. Only ever populated for KJV rows.", max_length=300, null=True),
        ),
    ]
