# Generated by Django 5.2 on 2026-09-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_wordtag_kjv_render_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='kjvstrongstag',
            name='morphology',
            field=models.CharField(blank=True, default='', help_text="Morphology code(s) for this word/phrase, e.g. 'strongMorph:TH8804'. Comma-joined when the source lists more than one for a single phrase-chunk. Blank when the source has none (most nouns/particles).", max_length=50),
        ),
    ]
