# Generated by Django 5.2 on 2026-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_kjvstrongstag_morphology'),
    ]

    operations = [
        migrations.AddField(
            model_name='kjvstrongstag',
            name='original_word',
            field=models.CharField(blank=True, default='', help_text='Hebrew/Greek script for this word, when the source provides it. Blank for some rows.', max_length=100),
        ),
        migrations.AddField(
            model_name='kjvstrongstag',
            name='transliteration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='kjvstrongstag',
            name='morphology',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='kjvstrongstag',
            name='surface_word',
            field=models.CharField(help_text='The KJV word/phrase as displayed', max_length=50),
        ),
    ]
